### ISSUE TITLE
how can i add multi messageChannel

### ISSUE THREAD

**Issue by ghost** [osimosu/jhipster-kafka#4]
with the demo application-dev.yml flowing config:

```
cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost
                    zk-nodes: localhost
            bindings:
                messageChannel:
                    destination: greetings
                    content-type: application/json
                subscribableChannel:
                    destination: greetings


```
how can i add multi messageChannel and subscribableChannel
